% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Taller 2- Evaluación de impacto},
  pdfauthor={Camila Caraballo, Laura Rivera},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Taller 2- Evaluación de impacto}
\author{Camila Caraballo, Laura Rivera}
\date{2025-09-2}

\begin{document}
\maketitle

\section{Taller 2- Variables
Instrumentales}\label{taller-2--variables-instrumentales}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Cargar liberias y paquetes}

\CommentTok{\#install.packages("haven") cual}
\CommentTok{\#install.packages("plm")}
\CommentTok{\#install.packages("skimr")}
\CommentTok{\#install.packages("dplyr")}
\CommentTok{\#install.packages("ggplot2")}
\CommentTok{\#install.packages("modelsummary")}


\FunctionTok{library}\NormalTok{(haven)}
\FunctionTok{library}\NormalTok{(plm)}
\FunctionTok{library}\NormalTok{(scales)}
\FunctionTok{library}\NormalTok{(skimr)}
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Adjuntando el paquete: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:plm':
## 
##     between, lag, lead
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(AER)        }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cargando paquete requerido: car
\end{verbatim}

\begin{verbatim}
## Cargando paquete requerido: carData
\end{verbatim}

\begin{verbatim}
## 
## Adjuntando el paquete: 'car'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:dplyr':
## 
##     recode
\end{verbatim}

\begin{verbatim}
## Cargando paquete requerido: lmtest
\end{verbatim}

\begin{verbatim}
## Cargando paquete requerido: zoo
\end{verbatim}

\begin{verbatim}
## 
## Adjuntando el paquete: 'zoo'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     as.Date, as.Date.numeric
\end{verbatim}

\begin{verbatim}
## Cargando paquete requerido: sandwich
\end{verbatim}

\begin{verbatim}
## Cargando paquete requerido: survival
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(fixest)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Adjuntando el paquete: 'fixest'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:scales':
## 
##     pvalue
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lmtest)}
\FunctionTok{library}\NormalTok{(sandwich)}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v forcats   1.0.0     v stringr   1.5.1
## v lubridate 1.9.4     v tibble    3.2.1
## v purrr     1.0.4     v tidyr     1.3.1
## v readr     2.1.5
\end{verbatim}

\begin{verbatim}
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::between()    masks plm::between()
## x readr::col_factor() masks scales::col_factor()
## x purrr::discard()    masks scales::discard()
## x dplyr::filter()     masks stats::filter()
## x dplyr::lag()        masks plm::lag(), stats::lag()
## x dplyr::lead()       masks plm::lead()
## x car::recode()       masks dplyr::recode()
## x purrr::some()       masks car::some()
## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(stargazer)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Please cite as: 
## 
##  Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.
##  R package version 5.2.3. https://CRAN.R-project.org/package=stargazer
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Leer archivo .dta}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read\_dta}\NormalTok{(}\StringTok{"oil\_windfall\_sin10perc.dta"}\NormalTok{)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{201613424}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsubsection{1. Ecuaciones}\label{ecuaciones}

\subparagraph{Especificación en niveles (OLS, Ecuación
1)}\label{especificaciuxf3n-en-niveles-ols-ecuaciuxf3n-1}

\[W_{m}= δ_1​+θ_1​R_m​+X_mρ_1​+u_{m1}​\]

En este modelo, \(W_m\) representa el conjunto de resultados económicos
a nivel de AMC que incluyen el gasto reportado en distintas partidas de
presupuesto a nivel municipal, provisión de bienes y servicios públicos,
transferencias, ingresos de los hogares y tasas de pobreza. A su vez,
\(R_m\) corresponde a una medida de los ingresos municipales y es la
variable explicativa principal. Finalmente, \(X_m\) reúne distintas
características geográficas de cada municipio, incluyendo su latitud y
longitud, si está ubicado en la costa, la distancia a las capitales
federal y estatal, un indicador de si es capital estatal, así como
efectos fijos por estado.

\subparagraph{Especificación VI (OLS, Ecuación 3 y
4)}\label{especificaciuxf3n-vi-ols-ecuaciuxf3n-3-y-4}

\[Y_{m,1970}=δ_3+η_0 Q_{m,2000}+X'_mρ_3+ w_{m3}\]

Donde \(Y_{m,1970}\) es el resultado socioeconómico en AMC para el año
1970 y se usa como ``placebo'' para probar que el instrumento no estaba
correlacionado con condiciones socioeconómicas históricas,
\(Q_{m,2000}\) hace referencia a la producción petrolera en el año 2000
en el municipio \(m\), el cual funciona como el instrumento para
regalías y \(Xm′\) es el vector de controles geográficos y estructurales
como latitud, longitud, si es costa, distancias a capitales, si es
capital estatal junto con efectos fijos estatales.

\[Y_{m,2002} = δ_4+η_4Q_{m,2002}+X'_mρ_4+w_{m4}\]

Donde \(Y_{m,1970}\) es el Producto Interno Bruto en 2002 del municipio
\(m\), \(Q_{m,2000}\) es la producción petrolera en el año 2000 en el
municipio \(m\). y \(X'_m\) es el vector de controles geográficos y
estructurales.

\subsubsection{2. Intuición
metodológica}\label{intuiciuxf3n-metodoluxf3gica}

\subparagraph{¿Cuál es la intuición detrás de implementar Variables
Instrumentales (VI) en vez de Mínimos Cuadrados Ordinarios (MCO)? En
este escenario: Mencione al menos un sesgo del cual podríamos estar
preocupados si interpretamos los efectos por MCO de manera causal.
¿Cuáles son los supuestos necesarios para que VI nos permita recuperar
el efecto causal de interés? ¿Son creíbles los supuestos?
Argumenten.}\label{cuuxe1l-es-la-intuiciuxf3n-detruxe1s-de-implementar-variables-instrumentales-vi-en-vez-de-muxednimos-cuadrados-ordinarios-mco-en-este-escenario-mencione-al-menos-un-sesgo-del-cual-podruxedamos-estar-preocupados-si-interpretamos-los-efectos-por-mco-de-manera-causal.-cuuxe1les-son-los-supuestos-necesarios-para-que-vi-nos-permita-recuperar-el-efecto-causal-de-interuxe9s-son-creuxedbles-los-supuestos-argumenten.}

La razón principal para emplear el método de variable instrumental es
que una estimación por Mínimos Cuadrados Ordinarios (MCO) podría arrojar
resultados sesgados porque los ingresos municipales no son estrictamente
exógenos. Municipios con poblaciones de mayores ingresos o con mayor
capacidad institucional pueden mostrar al mismo tiempo mejores
indicadores socioeconómicos, lo cual impediría identificar un efecto
puramente causal. Existe también la posibilidad de causalidad inversa en
la medida en que condiciones socioeconómicas más favorables permiten
recaudar más ingresos fiscales. Además, no puede descartarse la
influencia de factores no observados, como la calidad de las
instituciones locales o la existencia de redes clientelares, que
expliquen simultáneamente mayores ingresos y peores resultados en la
provisión de bienes y servicios públicos.

Ante estos problemas los autores recurren a la producción de petróleo
como instrumento de los ingresos municipales. La variación geográfica en
la producción se interpreta como un shock exógeno que incrementa los
recursos locales mediante regalías y permite recuperar el efecto causal
de esos ingresos extraordinarios sobre el gasto público y los resultados
sociales.

La validez de esta estrategia depende del cumplimiento de dos
condiciones. La primera es la relevancia, que implica que la producción
de petróleo \(Q_m\)\hspace{0pt} esté correlacionada con los ingresos
municipales \(R_m\)Los autores muestran evidencia a favor de este punto
al encontrar que un real adicional de producción petrolera se asocia con
un incremento promedio de tres centavos en los ingresos municipales. La
segunda es la exclusión, que exige que la producción de petróleo afecte
los resultados socioeconómicos \(W_m\) únicamente a través de los
ingresos municipales. Este supuesto se sostiene en el hecho de que los
campos petroleros se ubican costa afuera, son operados por Petrobras y
utilizan insumos y mano de obra altamente especializados que no
provienen de los municipios beneficiarios, lo que reduce la posibilidad
de un impacto directo sobre la provisión de servicios, las
transferencias o los ingresos de los hogares.

La extracción de petróleo mar adentro limita de manera importante la
existencia de derrames productivos locales y evita que los municipios
reciban beneficios económicos distintos a las transferencias fiscales.
Además, como las regalías se asignan según reglas legales vinculadas a
la ubicación geográfica de los campos, el ingreso municipal depende de
criterios externos y no de la capacidad de gestión local. Para reforzar
este argumento, los autores presentan pruebas de falsificación que
muestran que las condiciones socioeconómicas en 1970, antes de los
descubrimientos offshore, no predicen la producción futura de petróleo.
Esto sugiere que la asignación de los yacimientos no está asociada a
características históricas de desarrollo municipal sino que se comporta
de manera aleatoria una vez se controlan los factores geográficos.

En síntesis, los autores defienden de forma convincente que la
localización costa afuera de los yacimientos impide la existencia de un
canal productivo directo entre la actividad petrolera y el bienestar
local, de modo que la única vía de transmisión entre la abundancia de
petróleo y los resultados municipales es el aumento de regalías y
transferencias fiscales.

\subsubsection{3. Primera etapa}\label{primera-etapa}

\subparagraph{En una tabla, presenten los resultados de estimar la
primera etapa de la metodología de Variables Instrumentales. ¿Es el
instrumento relevante y fuerte? Contesten esta pregunta usando los dos
criterios recomendados en la clase
magistral.}\label{en-una-tabla-presenten-los-resultados-de-estimar-la-primera-etapa-de-la-metodologuxeda-de-variables-instrumentales.-es-el-instrumento-relevante-y-fuerte-contesten-esta-pregunta-usando-los-dos-criterios-recomendados-en-la-clase-magistral.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Eliminar aleatoriamente el 10\% de la base}

\CommentTok{\# Número exacto de filas a eliminar (10\% de la base)}
\NormalTok{eliminar }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(}\FloatTok{0.1} \SpecialCharTok{*} \FunctionTok{nrow}\NormalTok{(data))}

\CommentTok{\# Escoger aleatoriamente los índices a eliminar}
\NormalTok{drop\_index }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(data), }\AttributeTok{size =}\NormalTok{ eliminar)}

\CommentTok{\# Crear la submuestra eliminando esos índices}
\NormalTok{data\_final }\OtherTok{\textless{}{-}}\NormalTok{ data[}\SpecialCharTok{{-}}\NormalTok{drop\_index, ]}

\CommentTok{\# Solo municipios costeros que reciben petroleo }
\NormalTok{data\_final }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(data\_final, coastal }\SpecialCharTok{==} \DecValTok{1} \SpecialCharTok{\&}\NormalTok{ onshore }\SpecialCharTok{==} \DecValTok{0}\NormalTok{)}

\CommentTok{\# Observa base}
\FunctionTok{str}\NormalTok{(data\_final)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## tibble [149 x 22] (S3: tbl_df/tbl/data.frame)
##  $ new_code_1970_1997              : chr [1:149] "150410" "150430" "150440" "150790" ...
##   ..- attr(*, "label")= chr "AMC code"
##   ..- attr(*, "format.stata")= chr "%12s"
##  $ sigla                           : chr [1:149] "PA" "PA" "PA" "PA" ...
##   ..- attr(*, "label")= chr "State code"
##   ..- attr(*, "format.stata")= chr "%5s"
##  $ coastal                         : num [1:149] 1 1 1 1 1 1 1 1 1 1 ...
##   ..- attr(*, "label")= chr "1 if coastal AMC, 0 otherwise"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ onshore                         : num [1:149] 0 0 0 0 0 0 0 0 0 0 ...
##   ..- attr(*, "label")= chr "Onshore oil producer"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ dist_federal_capital1998        : num [1:149] 1658 1680 1666 1667 1665 ...
##   ..- attr(*, "label")= chr "Distance to the federal capital"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ dist_state_capital1998          : num [1:149] 124.6 140 121.2 81.8 108.6 ...
##   ..- attr(*, "label")= chr "Distance to the state capital"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ latitude1998                    : num [1:149] -0.794 -0.595 -0.717 -0.717 -0.729 ...
##   ..- attr(*, "label")= chr "Latitude"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ longitude1998                   : num [1:149] 47.6 47.6 47.7 48.5 47.8 ...
##   ..- attr(*, "label")= chr "Longitude"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ oilandgasvalue2000_cap          : num [1:149] 0 0 0 0 0 0 0 0 0 0 ...
##   ..- attr(*, "label")= chr "AMC oil output"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ prc_hhld_with_power_2000        : num [1:149] 83.3 56.6 87.1 80.5 85.9 ...
##   ..- attr(*, "label")= chr "% of households with electricity"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ welfare_2000_c                  : num [1:149] 0.6573 0.0199 0.465 12.0941 1.5343 ...
##   ..- attr(*, "label")= chr "Social transfers per capita"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ clroomsMunicipal_pop2005        : num [1:149] 0.00486 0.00602 0.00668 0.00571 0.00301 ...
##   ..- attr(*, "label")= chr "Clasrooms per million people (2005)"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ estab_mun2002_without_pop       : num [1:149] 0.001134 0.000492 0.000592 0.0003 0.000744 ...
##   ..- attr(*, "label")= chr "Clinics per million people (2002)"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ state_capital                   : num [1:149] 0 0 0 0 0 0 0 0 0 0 ...
##   ..- attr(*, "label")= chr "1 if state capital, 0 otherwise"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ km_paved_munic_c                : num [1:149] 0 0 0 0 0 0 0 0 0 0 ...
##   ..- attr(*, "label")= chr "Kms of paved roads per million people (2005)"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ pmun_exp_funct_educ_cult2000c   : num [1:149] 3.89 132.66 155.8 138.78 19.44 ...
##   ..- attr(*, "label")= chr "Expenditure: Education and culture"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ pmun_exp_funct_health_sanit2000c: num [1:149] -25 24.5 29.8 23 14.9 ...
##   ..- attr(*, "label")= chr "Expenditure: Helath and sanitization"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ pmun_exp_funct_hous_urban2000c  : num [1:149] 20.754 20.98 0.437 33.595 16.002 ...
##   ..- attr(*, "label")= chr "Expenditure: Housing and urban development"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ pmun_exp_funct_transport2000c   : num [1:149] -7.156 9.2818 8.1694 13.7065 0.0872 ...
##   ..- attr(*, "label")= chr "Expenditure: Transportation"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ pmun_exp_funct_welf2000c        : num [1:149] 14.17 22.32 4.22 10.59 3.28 ...
##   ..- attr(*, "label")= chr "Expenditure: Social transfers"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ p_hhld_abovestrandard_ppl_2000  : num [1:149] 100 100 100 100 100 ...
##   ..- attr(*, "label")= chr "% of popultaion not living in favelas"
##   ..- attr(*, "format.stata")= chr "%9.0g"
##  $ mun_budget_revenue2000_pred_c   : num [1:149] 304.5 263.9 297.2 324.1 79.3 ...
##   ..- attr(*, "label")= chr "AMC municipal revenues"
##   ..- attr(*, "format.stata")= chr "%9.0g"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Transformación de variables }
\NormalTok{data\_final }\OtherTok{\textless{}{-}}\NormalTok{ data\_final }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{rename}\NormalTok{(}
    \AttributeTok{revenue     =}\NormalTok{ mun\_budget\_revenue2000\_pred\_c,}
    \AttributeTok{oil\_pc      =}\NormalTok{ oilandgasvalue2000\_cap,}
    \AttributeTok{lat         =}\NormalTok{ latitude1998,}
    \AttributeTok{lon         =}\NormalTok{ longitude1998,}
    \AttributeTok{coast       =}\NormalTok{ coastal,}
    \AttributeTok{dist\_fedcap =}\NormalTok{ dist\_federal\_capital1998,}
    \AttributeTok{dist\_statecap =}\NormalTok{ dist\_state\_capital1998,}
    \AttributeTok{state\_cap   =}\NormalTok{ state\_capital,}
    \AttributeTok{state    =}\NormalTok{ sigla, }
    
\NormalTok{  )}
  
  
\CommentTok{\# Cambiar a tipo factor }
\NormalTok{data\_final }\OtherTok{\textless{}{-}}\NormalTok{ data\_final }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{mutate}\NormalTok{(}\AttributeTok{state =} \FunctionTok{as.factor}\NormalTok{(state))}

\CommentTok{\# Primera etapa con FE de estado }
\NormalTok{prim\_et }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(}
\NormalTok{  revenue }\SpecialCharTok{\textasciitilde{}}\NormalTok{ oil\_pc }\SpecialCharTok{+}\NormalTok{ lat }\SpecialCharTok{+}\NormalTok{ lon }\SpecialCharTok{+}\NormalTok{ coast }\SpecialCharTok{+}\NormalTok{ dist\_fedcap }\SpecialCharTok{+}\NormalTok{ dist\_statecap }\SpecialCharTok{+}\NormalTok{ state\_cap }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(state),}
  \AttributeTok{data =}\NormalTok{ data\_final}
\NormalTok{)}

\CommentTok{\#Resultados por cluster}
\NormalTok{vc }\OtherTok{\textless{}{-}} \FunctionTok{vcovCL}\NormalTok{(prim\_et, }\AttributeTok{cluster =} \SpecialCharTok{\textasciitilde{}}\NormalTok{ state, }\AttributeTok{type =} \StringTok{"HC1"}\NormalTok{)}
\NormalTok{ct }\OtherTok{\textless{}{-}} \FunctionTok{coeftest}\NormalTok{(prim\_et, }\AttributeTok{vcov =}\NormalTok{ vc)}

\CommentTok{\# Solo coeficientes a reportar y sus SE}
\NormalTok{vars\_keep }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"oil\_pc"}\NormalTok{,}\StringTok{"lat"}\NormalTok{,}\StringTok{"lon"}\NormalTok{,}\StringTok{"coast"}\NormalTok{,}\StringTok{"dist\_fedcap"}\NormalTok{,}\StringTok{"dist\_statecap"}\NormalTok{,}\StringTok{"state\_cap"}\NormalTok{)}
\NormalTok{idx }\OtherTok{\textless{}{-}} \FunctionTok{match}\NormalTok{(vars\_keep, }\FunctionTok{rownames}\NormalTok{(ct))}
\NormalTok{betas }\OtherTok{\textless{}{-}}\NormalTok{ ct[idx, }\StringTok{"Estimate"}\NormalTok{]}
\NormalTok{ses   }\OtherTok{\textless{}{-}}\NormalTok{ ct[idx, }\StringTok{"Std. Error"}\NormalTok{]}

\CommentTok{\#Tabulación de los resultados }
\FunctionTok{stargazer}\NormalTok{(}
\NormalTok{  prim\_et,}
  \AttributeTok{type =} \StringTok{"latex"}\NormalTok{,                    }
  \AttributeTok{coef =} \FunctionTok{list}\NormalTok{(betas),}
  \AttributeTok{se   =} \FunctionTok{list}\NormalTok{(ses),}
  \AttributeTok{keep =} \FunctionTok{paste0}\NormalTok{(}\StringTok{"\^{}("}\NormalTok{, }\FunctionTok{paste}\NormalTok{(vars\_keep, }\AttributeTok{collapse=}\StringTok{"|"}\NormalTok{), }\StringTok{")$"}\NormalTok{),}
  \AttributeTok{dep.var.labels   =} \StringTok{"Ingresos municipales"}\NormalTok{,}
  \AttributeTok{covariate.labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Producción de petróleo"}\NormalTok{,}\StringTok{"Latitud"}\NormalTok{,}\StringTok{"Longitud"}\NormalTok{,}
                       \StringTok{"Dummy costa"}\NormalTok{,}\StringTok{"Dist. capital federal"}\NormalTok{,}\StringTok{"Dist. capital estatal"}\NormalTok{,}\StringTok{"Dummy capital estatal"}\NormalTok{),}
  \AttributeTok{omit             =} \StringTok{"factor}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{(state\_id}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{)|}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{(Intercept}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{)"}\NormalTok{,}
  \AttributeTok{star.cutoffs     =} \FunctionTok{c}\NormalTok{(.}\DecValTok{10}\NormalTok{,.}\DecValTok{05}\NormalTok{,.}\DecValTok{01}\NormalTok{),}
  \AttributeTok{digits           =} \DecValTok{3}\NormalTok{,}
  \AttributeTok{title            =} \StringTok{"Primera etapa: ingresos municipales sobre producción petrolera y controles"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## % Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
## % Date and time: vie, sept. 05, 2025 - 8:13:07 p. m.
## \begin{table}[!htbp] \centering 
##   \caption{Primera etapa: ingresos municipales sobre producción petrolera y controles} 
##   \label{} 
## \begin{tabular}{@{\extracolsep{5pt}}lc} 
## \\[-1.8ex]\hline 
## \hline \\[-1.8ex] 
##  & \multicolumn{1}{c}{\textit{Dependent variable:}} \\ 
## \cline{2-2} 
## \\[-1.8ex] & Ingresos municipales \\ 
## \hline \\[-1.8ex] 
##  Producción de petróleo & 0.035$^{***}$ \\ 
##   & (0.002) \\ 
##   & \\ 
##  Latitud & 55.510$^{*}$ \\ 
##   & (28.647) \\ 
##   & \\ 
##  Longitud & 38.294 \\ 
##   & (43.702) \\ 
##   & \\ 
##  Dummy costa &  \\ 
##   &  \\ 
##   & \\ 
##  Dist. capital federal & $-$0.282 \\ 
##   & (0.239) \\ 
##   & \\ 
##  Dist. capital estatal & 0.241 \\ 
##   & (0.280) \\ 
##   & \\ 
##  Dummy capital estatal & 342.259$^{***}$ \\ 
##   & (118.171) \\ 
##   & \\ 
## \hline \\[-1.8ex] 
## Observations & 141 \\ 
## R$^{2}$ & 0.672 \\ 
## Adjusted R$^{2}$ & 0.611 \\ 
## Residual Std. Error & 194.287 (df = 118) \\ 
## F Statistic & 10.983$^{***}$ (df = 22; 118) \\ 
## \hline 
## \hline \\[-1.8ex] 
## \textit{Note:}  & \multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
## \end{tabular} 
## \end{table}
\end{verbatim}

Los resultados de esta primera etapa muestran que la producción de
petróleo es un instrumento relevante para explicar los ingresos
municipales pues la relación entre estas variables es estadísticamente
significativo incluso al controlar por factores geográficos. Dado que se
presenta un estadístico F de 10,9, el cual super el umbral de 10
recomendado, implica que el instrumento es lo suficientemente relevante.
Este coeficiente estimado implica que por cada real per cápita adicional
de producción petrolera, los municipios reciben en promedio 3,5 centavos
de ingresos. Este resultado coincide con los hallazgos del artículo de
investigación que interpretan la variacióon de la producción de petróleo
offshore como un choque exógeno que incrementa los ingresos municipales
a través de las regalías, reforzando la argumentación de su estrategia
de identificación.

\subsubsection{4. Segunda etapa}\label{segunda-etapa}

\subparagraph{En una tabla, presenten e interpreten los resultados de
estimar por VI el efecto de (mayores) ingresos públicos (producto del
petróleo) sobre el gasto público reportado en el año 2000 en Educación y
Cultura, Salud y Sanitización, Transporte y Transferencias
Sociales.}\label{en-una-tabla-presenten-e-interpreten-los-resultados-de-estimar-por-vi-el-efecto-de-mayores-ingresos-puxfablicos-producto-del-petruxf3leo-sobre-el-gasto-puxfablico-reportado-en-el-auxf1o-2000-en-educaciuxf3n-y-cultura-salud-y-sanitizaciuxf3n-transporte-y-transferencias-sociales.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_final }\OtherTok{\textless{}{-}}\NormalTok{ data\_final }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{rename}\NormalTok{(}
    \AttributeTok{amc\_code        =}\NormalTok{ new\_code\_1970\_1997,}
    \AttributeTok{per\_ho\_elec     =}\NormalTok{ prc\_hhld\_with\_power\_2000,}
    \AttributeTok{salon\_pob\_2005  =}\NormalTok{ clroomsMunicipal\_pop2005,}
    \AttributeTok{clinic\_pob\_2002 =}\NormalTok{ estab\_mun2002\_without\_pop,}
    \AttributeTok{km\_pob\_2005     =}\NormalTok{ km\_paved\_munic\_c,}
    \AttributeTok{ex\_edu\_cult        =}\NormalTok{ pmun\_exp\_funct\_educ\_cult2000c,}
    \AttributeTok{ex\_salud\_sani      =}\NormalTok{ pmun\_exp\_funct\_health\_sanit2000c,}
    \AttributeTok{ex\_desarrollo\_urb  =}\NormalTok{ pmun\_exp\_funct\_hous\_urban2000c, }
    \AttributeTok{ex\_transp          =}\NormalTok{ pmun\_exp\_funct\_transport2000c,}
    \AttributeTok{ex\_soc\_transf      =}\NormalTok{ pmun\_exp\_funct\_welf2000c,}
    \AttributeTok{perc\_nofavelas     =}\NormalTok{ p\_hhld\_abovestrandard\_ppl\_2000}
    
\NormalTok{  )}
\CommentTok{\#Agrupación de variables de interés}
\NormalTok{outcomes }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"ex\_edu\_cult"}\NormalTok{, }
  \StringTok{"ex\_salud\_sani"}\NormalTok{, }
  \StringTok{"ex\_desarrollo\_urb"}\NormalTok{, }
  \StringTok{"ex\_transp"}\NormalTok{, }\StringTok{"}
\StringTok{  ex\_soc\_transf"}
\NormalTok{)}

\NormalTok{data\_final}\SpecialCharTok{$}\NormalTok{state }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(data\_final}\SpecialCharTok{$}\NormalTok{state)}

\CommentTok{\#Estimación de la segunda etapa para cada una de las variables de resultado }

\NormalTok{m\_edu\_iv }\OtherTok{\textless{}{-}} \FunctionTok{ivreg}\NormalTok{(ex\_edu\_cult }\SpecialCharTok{\textasciitilde{}}\NormalTok{ revenue }\SpecialCharTok{+}\NormalTok{ lat }\SpecialCharTok{+}\NormalTok{ lon }\SpecialCharTok{+}\NormalTok{ coast }\SpecialCharTok{+}\NormalTok{ dist\_fedcap }\SpecialCharTok{+}\NormalTok{ dist\_statecap }\SpecialCharTok{+}\NormalTok{ state\_cap }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(state) }\SpecialCharTok{|}\NormalTok{ oil\_pc }\SpecialCharTok{+}\NormalTok{ lat }\SpecialCharTok{+}\NormalTok{ lon }\SpecialCharTok{+}\NormalTok{ coast }\SpecialCharTok{+}\NormalTok{ dist\_fedcap }\SpecialCharTok{+}\NormalTok{ dist\_statecap }\SpecialCharTok{+}\NormalTok{ state\_cap }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(state), }\AttributeTok{data =}\NormalTok{ data\_final)}

\NormalTok{m\_salud\_iv }\OtherTok{\textless{}{-}} \FunctionTok{ivreg}\NormalTok{(ex\_salud\_sani }\SpecialCharTok{\textasciitilde{}}\NormalTok{ revenue }\SpecialCharTok{+}\NormalTok{ lat }\SpecialCharTok{+}\NormalTok{ lon }\SpecialCharTok{+}\NormalTok{ coast }\SpecialCharTok{+}\NormalTok{ dist\_fedcap }\SpecialCharTok{+}\NormalTok{ dist\_statecap }\SpecialCharTok{+}\NormalTok{ state\_cap }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(state) }\SpecialCharTok{|}\NormalTok{oil\_pc }\SpecialCharTok{+}\NormalTok{ lat }\SpecialCharTok{+}\NormalTok{ lon }\SpecialCharTok{+}\NormalTok{ coast }\SpecialCharTok{+}\NormalTok{ dist\_fedcap }\SpecialCharTok{+}\NormalTok{ dist\_statecap }\SpecialCharTok{+}\NormalTok{ state\_cap }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(state), }\AttributeTok{data =}\NormalTok{ data\_final)}

\NormalTok{m\_urb\_iv  }\OtherTok{\textless{}{-}} \FunctionTok{ivreg}\NormalTok{(ex\_desarrollo\_urb }\SpecialCharTok{\textasciitilde{}}\NormalTok{ revenue }\SpecialCharTok{+}\NormalTok{ lat }\SpecialCharTok{+}\NormalTok{ lon }\SpecialCharTok{+}\NormalTok{ coast }\SpecialCharTok{+}\NormalTok{ dist\_fedcap }\SpecialCharTok{+}\NormalTok{ dist\_statecap }\SpecialCharTok{+}\NormalTok{ state\_cap }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(state) }\SpecialCharTok{|}\NormalTok{oil\_pc }\SpecialCharTok{+}\NormalTok{ lat }\SpecialCharTok{+}\NormalTok{ lon }\SpecialCharTok{+}\NormalTok{ coast }\SpecialCharTok{+}\NormalTok{ dist\_fedcap }\SpecialCharTok{+}\NormalTok{ dist\_statecap }\SpecialCharTok{+}\NormalTok{ state\_cap }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(state), }\AttributeTok{data =}\NormalTok{ data\_final)}

\NormalTok{m\_trans\_iv }\OtherTok{\textless{}{-}} \FunctionTok{ivreg}\NormalTok{(ex\_transp }\SpecialCharTok{\textasciitilde{}}\NormalTok{ revenue }\SpecialCharTok{+}\NormalTok{ lat }\SpecialCharTok{+}\NormalTok{ lon }\SpecialCharTok{+}\NormalTok{ coast }\SpecialCharTok{+}\NormalTok{ dist\_fedcap }\SpecialCharTok{+}\NormalTok{ dist\_statecap }\SpecialCharTok{+}\NormalTok{ state\_cap }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(state) }\SpecialCharTok{|}\NormalTok{oil\_pc }\SpecialCharTok{+}\NormalTok{ lat }\SpecialCharTok{+}\NormalTok{ lon }\SpecialCharTok{+}\NormalTok{ coast }\SpecialCharTok{+}\NormalTok{ dist\_fedcap }\SpecialCharTok{+}\NormalTok{ dist\_statecap }\SpecialCharTok{+}\NormalTok{ state\_cap }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(state), }\AttributeTok{data =}\NormalTok{ data\_final)}

\NormalTok{m\_soc\_iv   }\OtherTok{\textless{}{-}} \FunctionTok{ivreg}\NormalTok{(ex\_soc\_transf     }\SpecialCharTok{\textasciitilde{}}\NormalTok{ revenue }\SpecialCharTok{+}\NormalTok{ lat }\SpecialCharTok{+}\NormalTok{ lon }\SpecialCharTok{+}\NormalTok{ coast }\SpecialCharTok{+}\NormalTok{ dist\_fedcap }\SpecialCharTok{+}\NormalTok{ dist\_statecap }\SpecialCharTok{+}\NormalTok{ state\_cap }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(state) }\SpecialCharTok{|}\NormalTok{oil\_pc }\SpecialCharTok{+}\NormalTok{ lat }\SpecialCharTok{+}\NormalTok{ lon }\SpecialCharTok{+}\NormalTok{ coast }\SpecialCharTok{+}\NormalTok{ dist\_fedcap }\SpecialCharTok{+}\NormalTok{ dist\_statecap }\SpecialCharTok{+}\NormalTok{ state\_cap }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(state), }\AttributeTok{data =}\NormalTok{ data\_final)}

\CommentTok{\#Errores agrupados por Estado }
\NormalTok{vc }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(m) sandwich}\SpecialCharTok{::}\FunctionTok{vcovCL}\NormalTok{(m, }\AttributeTok{cluster =} \SpecialCharTok{\textasciitilde{}}\NormalTok{ state, }\AttributeTok{type =} \StringTok{"HC1"}\NormalTok{)}
\NormalTok{ses }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(}\FunctionTok{list}\NormalTok{(m\_edu\_iv,m\_salud\_iv,m\_urb\_iv,m\_trans\_iv,m\_soc\_iv), }\ControlFlowTok{function}\NormalTok{(m) }\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{diag}\NormalTok{(}\FunctionTok{vc}\NormalTok{(m))))}

\CommentTok{\#Presentación de resultados en tabla}
\FunctionTok{stargazer}\NormalTok{(}
\NormalTok{  m\_edu\_iv,m\_salud\_iv,m\_trans\_iv,m\_soc\_iv,}
  \AttributeTok{type =} \StringTok{"latex"}\NormalTok{, }\AttributeTok{se =}\NormalTok{ ses,}
  \AttributeTok{dep.var.labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Gasto Educación/Cultura"}\NormalTok{,}\StringTok{"Gasto Salud/Saneamiento"}\NormalTok{,}\StringTok{"Gasto Transporte"}\NormalTok{,}\StringTok{"Gasto Asistencia Social"}\NormalTok{),}
  \AttributeTok{covariate.labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Ingresos (IV)"}\NormalTok{,}\StringTok{"Latitud"}\NormalTok{,}\StringTok{"Longitud"}\NormalTok{,}\StringTok{"Costa"}\NormalTok{,}\StringTok{"Dist. capital federal"}\NormalTok{,}\StringTok{"Dist. capital estatal"}\NormalTok{,}\StringTok{"Capital estatal"}\NormalTok{),}
  \AttributeTok{omit =} \StringTok{"factor}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{(state}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{)|}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{(Intercept}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{)"}\NormalTok{, }\AttributeTok{omit.labels =} \StringTok{"Dummies de estado"}\NormalTok{,}
  \AttributeTok{star.cutoffs =} \FunctionTok{c}\NormalTok{(.}\DecValTok{10}\NormalTok{,.}\DecValTok{05}\NormalTok{,.}\DecValTok{01}\NormalTok{), }\AttributeTok{digits =} \DecValTok{3}\NormalTok{,}
  \AttributeTok{title =} \StringTok{"Segunda etapa (IV): ingresos instrumentados y gastos por función"}\NormalTok{,}
  \AttributeTok{notes =} \StringTok{"Errores estándar robustos agrupados por estado entre paréntesis."}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## % Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
## % Date and time: vie, sept. 05, 2025 - 8:13:07 p. m.
## \begin{table}[!htbp] \centering 
##   \caption{Segunda etapa (IV): ingresos instrumentados y gastos por función} 
##   \label{} 
## \begin{tabular}{@{\extracolsep{5pt}}lcccc} 
## \\[-1.8ex]\hline 
## \hline \\[-1.8ex] 
##  & \multicolumn{4}{c}{\textit{Dependent variable:}} \\ 
## \cline{2-5} 
## \\[-1.8ex] & Gasto Educación/Cultura & Gasto Salud/Saneamiento & Gasto Transporte & Gasto Asistencia Social \\ 
## \\[-1.8ex] & (1) & (2) & (3) & (4)\\ 
## \hline \\[-1.8ex] 
##  Ingresos (IV) & 0.139$^{***}$ & 0.109$^{***}$ & 0.123$^{***}$ & 0.052$^{***}$ \\ 
##   & (0.006) & (0.005) & (0.014) & (0.005) \\ 
##   & & & & \\ 
##  Latitud & 4.708 & $-$1.942 & 0.248 & 1.919 \\ 
##   & (5.242) & (2.972) & (4.758) & (3.622) \\ 
##   & & & & \\ 
##  Longitud & 6.595 & 0.036 & $-$6.448 & 0.623 \\ 
##   & (5.730) & (3.036) & (7.160) & (4.159) \\ 
##   & & & & \\ 
##  Costa &  &  &  &  \\ 
##   &  &  &  &  \\ 
##   & & & & \\ 
##  Dist. capital federal & $-$0.027 & $-$0.090$^{**}$ & $-$0.049 & 0.012 \\ 
##   & (0.048) & (0.042) & (0.044) & (0.045) \\ 
##   & & & & \\ 
##  Dist. capital estatal & 0.033 & 0.032 & 0.002 & 0.022 \\ 
##   & (0.055) & (0.028) & (0.056) & (0.039) \\ 
##   & & & & \\ 
##  Capital estatal & $-$6.907 & 17.773 & $-$25.221 & 53.113$^{***}$ \\ 
##   & (15.521) & (25.609) & (28.563) & (14.478) \\ 
##   & & & & \\ 
##  Constant & $-$88.719 & 137.156 & 259.969 & $-$29.490 \\ 
##   & (186.855) & (108.802) & (293.984) & (157.680) \\ 
##   & & & & \\ 
## \hline \\[-1.8ex] 
## Dummies de estado & Yes & Yes & Yes & Yes \\ 
## \hline \\[-1.8ex] 
## Observations & 141 & 141 & 141 & 141 \\ 
## R$^{2}$ & 0.750 & 0.715 & 0.521 & 0.604 \\ 
## Adjusted R$^{2}$ & 0.703 & 0.662 & 0.432 & 0.530 \\ 
## Residual Std. Error (df = 118) & 40.005 & 30.667 & 31.476 & 20.257 \\ 
## \hline 
## \hline \\[-1.8ex] 
## \textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
##  & \multicolumn{4}{r}{Errores estándar robustos agrupados por estado entre paréntesis.} \\ 
## \end{tabular} 
## \end{table}
\end{verbatim}

Los resultados de la estimación mediante variables instrumentales
confirman que un aumento en los ingresos municipales predichos por la
producción de petróleo y gas se traduce en mayores niveles de gasto
público en los distintos sectores analizados para el año 2000. Este
hallazgo muestra una relación positiva y estadísticamente significativa
entre los recursos fiscales extraordinarios y el gasto municipal, lo que
respalda la hipótesis de que las regalías derivadas de la explotación
petrolera tienen un impacto directo sobre la provisión de bienes y
servicios públicos.

En el sector de Educación y Cultura, el coeficiente estimado es de
0.139, lo que implica que un incremento de una unidad en los ingresos
municipales predichos se asocia con un aumento cercano a 0.14 unidades
en el gasto destinado a este sector. Este resultado, significativo al
1\%, evidencia que la inversión en capital humano constituye una
prioridad en el uso de los recursos adicionales. En el ámbito de Salud y
Saneamiento, el coeficiente de 0.109, también significativo, sugiere un
patrón similar: los municipios con mayores ingresos derivados del
petróleo tienden a asignar más recursos al fortalecimiento de la
infraestructura y los servicios de salud, mejorando así la cobertura y
la calidad en este campo.

El gasto en Transporte presenta un coeficiente de 0.123, significativo
al 1\%, lo que indica que los ingresos extraordinarios también se
destinan con fuerza a la construcción y mantenimiento de infraestructura
vial y de transporte. Por su parte, las Transferencias Sociales muestran
un coeficiente positivo de 0.052, estadísticamente significativo aunque
de menor magnitud en comparación con los otros sectores. Esto revela
que, aunque los recursos petroleros se utilizan para apoyar programas de
bienestar social, su peso relativo es menor frente a las áreas de
educación, salud y transporte.

En conjunto, los resultados muestran que los choques positivos en
ingresos municipales vinculados a la producción de petróleo offshore
generan un aumento sustancial en el gasto público local, con mayor
intensidad en los sectores de Educación, Salud y Transporte. Esta
evidencia sugiere que los municipios costeros beneficiados canalizan los
recursos principalmente hacia servicios públicos esenciales, mientras
que las transferencias sociales reciben un refuerzo menor, lo que
refleja una priorización clara en la asignación del gasto.

\subsubsection{5. Forma reducida}\label{forma-reducida}

\subparagraph{En una tabla, presenten e interpreten los resultados de
estimar por VI el efecto de (mayores) ingresos públicos (producto del
petróleo) sobre las variables efectivas de bienestar. En particular,
sobre proporción de personas que no viven en favelas en 2000 y el número
de salones por millón de habitantes en el 2005. ¿Qué indican sus
resultados? ¿Mayores ingresos públicos resultan en niveles del bienestar
medido a través de estas variables?. En texto describa los resultados
para la primera variable
.}\label{en-una-tabla-presenten-e-interpreten-los-resultados-de-estimar-por-vi-el-efecto-de-mayores-ingresos-puxfablicos-producto-del-petruxf3leo-sobre-las-variables-efectivas-de-bienestar.-en-particular-sobre-proporciuxf3n-de-personas-que-no-viven-en-favelas-en-2000-y-el-nuxfamero-de-salones-por-milluxf3n-de-habitantes-en-el-2005.-quuxe9-indican-sus-resultados-mayores-ingresos-puxfablicos-resultan-en-niveles-del-bienestar-medido-a-travuxe9s-de-estas-variables.-en-texto-describa-los-resultados-para-la-primera-variable-.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Personas que no viven en favelas en 2000}
\NormalTok{m\_nofav }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(perc\_nofavelas }\SpecialCharTok{\textasciitilde{}}\NormalTok{ oil\_pc }\SpecialCharTok{+}\NormalTok{ lat }\SpecialCharTok{+}\NormalTok{ lon }\SpecialCharTok{+}\NormalTok{ coast }\SpecialCharTok{+}\NormalTok{ dist\_fedcap }\SpecialCharTok{+}\NormalTok{ dist\_statecap }\SpecialCharTok{+}\NormalTok{ state\_cap }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(state), }\AttributeTok{data =}\NormalTok{ data\_final)}

\CommentTok{\# Número de salones por millón de habitantes en el 2005.}
\NormalTok{m\_classrooms }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(salon\_pob\_2005 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ oil\_pc }\SpecialCharTok{+}\NormalTok{ lat }\SpecialCharTok{+}\NormalTok{ lon }\SpecialCharTok{+}\NormalTok{ coast }\SpecialCharTok{+}\NormalTok{ dist\_fedcap }\SpecialCharTok{+}\NormalTok{ dist\_statecap }\SpecialCharTok{+}\NormalTok{ state\_cap }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(state), }\AttributeTok{data =}\NormalTok{ data\_final)}

\CommentTok{\# Errores estándar robustos agrupados por estado}
\NormalTok{se\_nofav      }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{diag}\NormalTok{(}\FunctionTok{vcovCL}\NormalTok{(m\_nofav, }\AttributeTok{cluster =} \SpecialCharTok{\textasciitilde{}}\NormalTok{ state, }\AttributeTok{type =} \StringTok{"HC1"}\NormalTok{)))}
\NormalTok{se\_classrooms }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{diag}\NormalTok{(}\FunctionTok{vcovCL}\NormalTok{(m\_classrooms, }\AttributeTok{cluster =} \SpecialCharTok{\textasciitilde{}}\NormalTok{ state, }\AttributeTok{type =} \StringTok{"HC1"}\NormalTok{)))}

\CommentTok{\#Tabulación forma reducida}
\FunctionTok{stargazer}\NormalTok{(}
\NormalTok{  m\_nofav, m\_classrooms,}
  \AttributeTok{type             =} \StringTok{"latex"}\NormalTok{,   }
  \AttributeTok{se               =} \FunctionTok{list}\NormalTok{(se\_nofav, se\_classrooms),}
  \AttributeTok{dep.var.labels   =} \FunctionTok{c}\NormalTok{(}\StringTok{"No{-}favelas"}\NormalTok{, }\StringTok{"Salones por millón de habitantes"}\NormalTok{),}
  \AttributeTok{covariate.labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Producción de petróleo per cápita (instrumento)"}\NormalTok{),}
  \AttributeTok{keep             =} \StringTok{"\^{}oil\_pc$"}\NormalTok{,}
  \AttributeTok{omit             =} \StringTok{"factor}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{(state\_id}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{)|lat|lon|coast|dist\_fedcap|dist\_statecap|state\_cap|Intercept"}\NormalTok{,}
  \AttributeTok{omit.labels      =} \StringTok{"Controles y efectos fijos"}\NormalTok{,}
  \AttributeTok{star.cutoffs     =} \FunctionTok{c}\NormalTok{(.}\DecValTok{10}\NormalTok{,.}\DecValTok{05}\NormalTok{,.}\DecValTok{01}\NormalTok{),}
  \AttributeTok{digits           =} \DecValTok{3}\NormalTok{,}
  \AttributeTok{title            =} \StringTok{"Forma reducida: efecto del petróleo sobre indicadores de bienestar"}\NormalTok{,}
  \AttributeTok{notes            =} \StringTok{"Errores estándar robustos agrupados por estado entre paréntesis. Modelos incluyen controles geográficos y efectos fijos de estado."}\NormalTok{,}
  \AttributeTok{notes.align      =} \StringTok{"l"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## % Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
## % Date and time: vie, sept. 05, 2025 - 8:13:08 p. m.
## \begin{table}[!htbp] \centering 
##   \caption{Forma reducida: efecto del petróleo sobre indicadores de bienestar} 
##   \label{} 
## \begin{tabular}{@{\extracolsep{5pt}}lcc} 
## \\[-1.8ex]\hline 
## \hline \\[-1.8ex] 
##  & \multicolumn{2}{c}{\textit{Dependent variable:}} \\ 
## \cline{2-3} 
## \\[-1.8ex] & No-favelas & Salones por millón de habitantes \\ 
## \\[-1.8ex] & (1) & (2)\\ 
## \hline \\[-1.8ex] 
##  Producción de petróleo per cápita (instrumento) & $-$0.0005$^{***}$ & 0.00000$^{**}$ \\ 
##   & (0.00004) & (0.00000) \\ 
##   & & \\ 
## \hline \\[-1.8ex] 
## Controles y efectos fijos & Yes & Yes \\ 
## \hline \\[-1.8ex] 
## Observations & 149 & 149 \\ 
## R$^{2}$ & 0.275 & 0.454 \\ 
## Adjusted R$^{2}$ & 0.148 & 0.358 \\ 
## Residual Std. Error (df = 126) & 5.015 & 0.002 \\ 
## F Statistic (df = 22; 126) & 2.169$^{***}$ & 4.755$^{***}$ \\ 
## \hline 
## \hline \\[-1.8ex] 
## \textit{Note:}  & \multicolumn{2}{l}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
##  & \multicolumn{2}{l}{Errores estándar robustos agrupados por estado entre paréntesis. Modelos incluyen controles geográficos y efectos fijos de estado.} \\ 
## \end{tabular} 
## \end{table}
\end{verbatim}

El coeficiente estimado de --0.0005 implica que, por cada aumento de una
unidad en la producción de petróleo per cápita, la proporción de
personas que no viven en favelas disminuye en 0.05 puntos porcentuales.
Aunque el valor numérico del efecto puede parecer pequeño, el hecho de
que sea altamente significativo estadísticamente al 1\% indica que la
relación es sistemática y no producto del azar.

Desde el punto de vista económico, este resultado es relevante porque
muestra que los incrementos en la producción petrolera no se traducen en
mejoras en las condiciones habitacionales, sino más bien en un ligero
deterioro. Esto puede interpretarse como evidencia de que los ingresos
del petróleo no se transforman de manera efectiva en políticas que
reduzcan la informalidad en la vivienda. Por tanto, aun siendo
cuantitativamente modesto, el hallazgo es importante porque cuestiona la
eficacia con que los municipios canalizan los recursos petroleros hacia
mejoras en bienestar habitacional al menos en esta variable de análisis.

\end{document}
